// ==UserScript==
// @name         CC Switch Importer for linux.do
// @namespace    https://github.com/Super-YYQ/ccswitch-linuxdo-importer
// @version      1.1.6
// @description  选中 linux.do 分享文本，一键导入 CC Switch（Claude Code / Codex，自动识别模型）
// @author       CC Switch Importer Contributors
// @match        https://linux.do/*
// @match        https://www.linux.do/*
// @grant        GM_setClipboard
// @grant        GM_notification
// @run-at       document-idle
// @noframes
// @license      MIT
// @homepageURL  https://github.com/Super-YYQ/ccswitch-linuxdo-importer
// @supportURL   https://github.com/Super-YYQ/ccswitch-linuxdo-importer/issues
// @downloadURL  https://raw.githubusercontent.com/Super-YYQ/ccswitch-linuxdo-importer/main/userscript/ccswitch-linuxdo-importer.user.js
// @updateURL    https://raw.githubusercontent.com/Super-YYQ/ccswitch-linuxdo-importer/main/userscript/ccswitch-linuxdo-importer.user.js
// ==/UserScript==

/* eslint-disable */
/* generated by scripts/build.mjs — edit userscript/lib/* + ui-main.js then rebuild */

;(function (global) {
  'use strict';

  const SCRIPT_VERSION = "1.1.6";

  // ─── core (parse / classify / deeplink) ───
/**
 * Pure parse / classify / deeplink helpers for CC Switch linux.do importer.
 * Used by Node tests and inlined into the Tampermonkey userscript.
 */

const MIN_SELECTION_LEN = 20
/** Hard caps so adversarial / huge selections cannot freeze the tab. */
const MAX_SELECTION_LEN = 64 * 1024
const MAX_DECODED_LEN = 64 * 1024
const MAX_JSON_OBJECTS = 16
const MAX_URLS = 8
const MAX_KEYS = 8
const MAX_CANDIDATES = 12

const ENV_URL_KEYS = [
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_API_BASE',
  'CLAUDE_BASE_URL',
  'OPENAI_BASE_URL',
  'OPENAI_API_BASE',
  'CODEX_BASE_URL',
  'BASE_URL',
  'API_BASE_URL',
]

const ENV_KEY_KEYS = [
  'ANTHROPIC_AUTH_TOKEN',
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_API_TOKEN',
  'CLAUDE_API_KEY',
  'OPENAI_API_KEY',
  'OPENAI_AUTH_TOKEN',
  'CODEX_API_KEY',
  'API_KEY',
  'APIKEY',
  'AUTH_TOKEN',
  'TOKEN',
]

const URL_RE = /https?:\/\/[^\s"'`<>，。；、）)\]}]+/gi
const SK_ANT_RE = /sk-ant-[A-Za-z0-9_\-]{10,}/g
const SK_RE = /sk-[A-Za-z0-9_\-]{16,}/g
const BEARER_RE = /Bearer\s+([A-Za-z0-9_\-.]{16,})/gi
// CJK / fullwidth punct count as token boundaries — linux.do often glues base64 after Chinese prose
const B64_BOUNDARY_L = '(?:^|[\\s"\'`：:，。；、！？]|(?<=[一-鿿]))'
const B64_BOUNDARY_R = '(?:$|[\\s"\'`，。；、！？]|(?=[一-鿿]))'
const BASE64_RE = new RegExp(`${B64_BOUNDARY_L}([A-Za-z0-9+/]{40,}={0,2})${B64_BOUNDARY_R}`, 'g')
const DEEPLINK_RE = /ccswitch:\/\/[^\s"'`<>]+/i
// Known API key prefixes (sk-/g2a_/tp- token-plan, plus rare vendor tags)
const KEY_PREFIX_RE = /^(sk-ant-|sk-|g2a_|tp-|nk-|pk-|rk-)/i
const KEY_PREFIX_BODY_RE = /^(sk-ant-|sk-|g2a_|tp-|nk-|pk-|rk-|Bearer\s)/i
const VENDOR_KEY_RE = /\b(?:g2a_|tp-|nk-|pk-|rk-)[A-Za-z0-9_\-]{8,}\b/g

/**
 * @typedef {'claude'|'codex'|null} AppKind
 * @typedef {'deeplink'|'base64'|'json'|'env'|'toml'|'mixed'} SourceKind
 * @typedef {{ endpoint: string|null, apiKey: string|null }} CandidatePair
 * @typedef {{
 *   name: string,
 *   app: AppKind,
 *   endpoint: string|null,
 *   apiKey: string|null,
 *   config: string|null,
 *   configFormat: 'json'|'toml'|null,
 *   source: SourceKind,
 *   confidence: number,
 *   candidateCount: number,
 *   candidateIndex: number,
 *   candidates: CandidatePair[],
 *   warnings: string[],
 *   deeplink?: string|null,
 *   models?: string[]
 * }} ParseResult
 */

/**
 * @param {string} text
 * @returns {ParseResult|null}
 */
function parseShareText(text) {
  if (text == null) return null
  let raw = normalizeShareText(text)
  if (raw.length < MIN_SELECTION_LEN) return null
  const oversized = raw.length > MAX_SELECTION_LEN
  if (oversized) raw = raw.slice(0, MAX_SELECTION_LEN)

  let cleaned = repairBrokenBase64(stripMarkdownFences(raw))

  // 1. Existing ccswitch deep link (provider only)
  const deep = extractDeeplink(cleaned)
  if (deep) {
    const fromLink = parseDeeplink(deep)
    if (fromLink) {
      fromLink.deeplink = deep
      if (oversized) {
        fromLink.warnings = [...(fromLink.warnings || []), '选区过大，已截断后再解析']
      }
      return fromLink
    }
    // Non-provider / malformed: strip so mixed path cannot harvest apiKey from querystring
    cleaned = cleaned.split(deep).join(' ')
  }

  // 2–6. Prefer complete (endpoint+key) results; otherwise stitch partial hits.
  // Partial JSON from Discourse linkify must not block mixed/base64 key recovery.
  const b64 = tryParseBase64(cleaned)
  const json = tryParseJson(cleaned)
  const toml = tryParseTomlLike(cleaned)
  const env = tryParseEnv(cleaned)
  const mixed = tryParseMixed(cleaned)
  const result = finalizeResult(mergeParseResults([b64, json, toml, env, mixed]), cleaned)
  if (result && oversized) {
    result.warnings = [...(result.warnings || []), '选区过大，已截断后再解析']
  }
  return result
}

/**
 * Prefer a result that has both endpoint+key; otherwise stitch the best fields together.
 * @param {Array<ParseResult|null|undefined>} candidates
 * @returns {ParseResult|null}
 */
function mergeParseResults(candidates) {
  const list = candidates.filter(Boolean)
  if (list.length === 0) return null

  const complete = list
    .filter((r) => r.endpoint && r.apiKey)
    .sort((a, b) => (b.confidence || 0) - (a.confidence || 0))
  if (complete[0]) return complete[0]

  let best = { ...list[0] }
  for (const r of list) {
    if (!best.endpoint && r.endpoint) best.endpoint = r.endpoint
    if (!best.apiKey && r.apiKey) best.apiKey = r.apiKey
    if (
      (!best.name || String(best.name).startsWith('linuxdo-')) &&
      r.name &&
      !String(r.name).startsWith('linuxdo-')
    ) {
      best.name = r.name
    }
    if ((r.candidates?.length || 0) > (best.candidates?.length || 0)) {
      best.candidates = r.candidates
      best.candidateIndex = r.candidateIndex || 0
      best.candidateCount = r.candidates.length
    }
    if ((r.confidence || 0) > (best.confidence || 0)) {
      best.source = r.source
      best.confidence = r.confidence
      best.warnings = r.warnings || best.warnings
      best.candidateCount = Math.max(best.candidateCount || 1, r.candidateCount || 1)
      best.app = r.app != null ? r.app : best.app
    }
  }
  if (!best.app) best.app = classifyApp('', best)
  best.warnings = buildWarnings(best)
  best.confidence = scoreFields(best, best.app)
  return best.endpoint || best.apiKey ? best : null
}

/**
 * Strip Discourse/selection noise that breaks key/base64 matching.
 * @param {string} text
 */
function normalizeShareText(text) {
  return String(text)
    // ZWSP/ZWNJ/ZWJ, BOM, soft-hyphen, word-joiner
    .replace(/[\u200B-\u200D\uFEFF\u00AD\u2060]/g, '')
    // nbsp / narrow nbsp / figure space
    .replace(/[\u00A0\u202F\u2007]/g, ' ')
    // smart / curly quotes \u2192 ASCII (Discourse / paste noise)
    .replace(/[\u201C\u201D\u201E\u201F\u2033\u2036]/g, '"')
    .replace(/[\u2018\u2019\u201A\u201B\u2032\u2035]/g, "'")
    .replace(/\r\n?/g, '\n')
    .trim()
}

/**
 * Merge real URLs from selected <a href> into selection text.
 * Discourse often shows link text as "base url" while the real endpoint only lives in href;
 * window.getSelection().toString() drops those hrefs.
 *
 * @param {string} text - selection.toString()
 * @param {Array<{text?: string, href?: string}>} anchors
 * @returns {string}
 */
function enrichTextWithAnchorHrefs(text, anchors) {
  const base = text == null ? '' : String(text)
  if (!anchors || anchors.length === 0) return base

  const existing = new Set(matchAll(base, URL_RE).map(cleanUrl))
  for (const u of existing) {
    // also mark raw occurrences
    if (base.includes(u)) existing.add(u)
  }

  /** @type {Array<{label: string, href: string, preferred: boolean}>} */
  const toAdd = []
  for (const a of anchors) {
    if (!a) continue
    const href = unwrapHref(a.href)
    if (!href || !/^https?:\/\//i.test(href)) continue
    const cleaned = cleanUrl(href)
    if (!cleaned || existing.has(cleaned) || base.includes(cleaned)) {
      if (cleaned) existing.add(cleaned)
      continue
    }
    const label = String(a.text || '').trim().replace(/\s+/g, ' ')
    const preferred = isUrlLinkLabel(label)
    toAdd.push({ label, href: cleaned, preferred })
    existing.add(cleaned)
  }

  if (toAdd.length === 0) return base

  // Prefer labeled base-url anchors first
  toAdd.sort((a, b) => Number(b.preferred) - Number(a.preferred))

  let out = base
  const appended = []
  for (const item of toAdd) {
    if (item.preferred && item.label) {
      // Replace bare labels like "base url" with "base url\uFF1Ahttps://..." for labeled extract.
      // Do NOT replace inside JSON quotes \u2014 Discourse often linkifies the JSON key/value
      // "url", and rewriting `"url"` \u2192 `url\uFF1Ahttps://...` corrupts the object and drops fields.
      const labelRe = new RegExp(
        `(?<!["'\\w./])(${escapeRegExp(item.label)})(?![\\w"'])(?!\\s*[:\uFF1A=]\\s*https?:)`,
        'i',
      )
      if (labelRe.test(out)) {
        out = out.replace(labelRe, `$1\uFF1A${item.href}`)
        continue
      }
      appended.push(`${item.label}\uFF1A${item.href}`)
    } else {
      appended.push(item.href)
    }
  }
  if (appended.length) out = `${out}\n${appended.join('\n')}`
  return out
}

/** Visible link labels that usually stand for the API base URL on linux.do shares. */
function isUrlLinkLabel(label) {
  if (!label) return false
  const s = label.trim()
  if (
    /^(?:url|base\s*url|base[_-]?url|endpoint|api\s*base|api[_-]?base|host|\u5730\u5740|\u63A5\u53E3|\u94FE\u63A5)(?:\b|[\uFF08(]|\d|$)/i.test(
      s,
    )
  ) {
    return true
  }
  // "base url 2", "Base URL", etc.
  if (/base\s*url|endpoint|base[_-]?url/i.test(s) && s.length <= 40) return true
  return false
}

/**
 * Normalize anchor href: keep http(s), unwrap common click-trackers / nested URLs.
 * @param {string|null|undefined} href
 * @returns {string|null}
 */
function unwrapHref(href) {
  if (!href) return null
  let h = String(href).trim()
  if (!h) return null
  // ignore non-navigational schemes
  if (/^(javascript|mailto|tel|data|#):/i.test(h)) return null
  // nested https inside tracking / redirect URLs
  try {
    const m = h.match(/https?:\/\/[^\s"'<>]+/i)
    if (m) {
      // if the whole thing is already http(s), prefer parsing query redirects
      if (/^https?:\/\//i.test(h)) {
        try {
          const u = new URL(h)
          for (const key of ['url', 'u', 'target', 'redirect', 'to', 'link', 'dest']) {
            const v = u.searchParams.get(key)
            if (v && /^https?:\/\//i.test(v)) return cleanUrl(v)
          }
        } catch {
          /* keep */
        }
        return cleanUrl(h)
      }
      return cleanUrl(m[0])
    }
  } catch {
    /* keep */
  }
  return null
}

/**
 * Re-join base64 tokens broken by spaces/newlines if the join decodes to a key.
 * @param {string} text
 */
function repairBrokenBase64(text) {
  // spaces inside an otherwise base64-ish run
  let out = text.replace(
    /(?:^|[\s"'`])((?:[A-Za-z0-9+/_-]{6,}={0,2}[\s\u00AD]+){1,}[A-Za-z0-9+/_-]{6,}={0,2})(?=$|[\s"'`])/gm,
    (full, group) => {
      const prefix = full.slice(0, full.length - group.length)
      const joined = group.replace(/[\s\u00AD]+/g, '')
      if (joined.length < 24) return full
      try {
        const d = base64Decode(joined).trim()
        if (KEY_PREFIX_RE.test(d) && !/\s/.test(d) && d.length >= 8) {
          return prefix + joined
        }
      } catch {
        /* keep */
      }
      return full
    },
  )
  // adjacent pure-base64 lines
  out = out.replace(
    /(^|\n)([A-Za-z0-9+/_-]{12,}={0,2})\n([A-Za-z0-9+/_-]{12,}={0,2})(?=\n|$)/gm,
    (full, lead, a, b) => {
      const joined = a + b
      try {
        const d = base64Decode(joined).trim()
        if (KEY_PREFIX_RE.test(d) && !/\s/.test(d)) return `${lead}${joined}`
      } catch {
        /* keep */
      }
      return full
    },
  )
  return out
}

/**
 * Single exit for apiKey: decode body (b64/hex/watermark) + optional vendor prefix from prose.
 * Intermediate parsers should pass raw tokens; finalize always runs this once.
 * @param {string|null|undefined} raw
 * @param {string} [shareText]
 * @returns {string|null|undefined}
 */
function normalizeApiKey(raw, shareText = '') {
  if (raw == null || raw === '') return raw
  const decoded = decodeKeyBody(raw)
  return applyKeyPrefixHints(decoded, shareText)
}

/** Final pass: normalize keys/endpoints once, clamp confidence. */
function finalizeResult(result, text = '') {
  if (!result) return null

  const beforeKey = result.apiKey
  const fixKey = (k) => (k ? normalizeApiKey(k, text) : k)

  if (result.apiKey) result.apiKey = fixKey(result.apiKey)
  if (result.endpoint) result.endpoint = cleanUrl(normalizeShareText(result.endpoint))

  if (result.candidates?.length) {
    result.candidates = result.candidates.map((c) => ({
      endpoint: c.endpoint ? cleanUrl(normalizeShareText(c.endpoint)) : c.endpoint,
      apiKey: fixKey(c.apiKey),
    }))
    const i = Math.max(0, Math.min(result.candidateIndex || 0, result.candidates.length - 1))
    result.candidateIndex = i
    result.apiKey = result.candidates[i].apiKey
    result.endpoint = result.candidates[i].endpoint
  }

  if (result.apiKey && beforeKey) {
    const bodyOnly = decodeKeyBody(beforeKey)
    if (hasKeyPrefix(result.apiKey) && bodyOnly && !hasKeyPrefix(bodyOnly) && result.apiKey !== bodyOnly) {
      const prefix = (result.apiKey.match(KEY_PREFIX_RE) || [])[1] || 'sk-'
      const note = `已根据文案补上 ${prefix} 前缀`
      if (!result.warnings) result.warnings = []
      if (!result.warnings.includes(note)) result.warnings.push(note)
    }
  }

  if (typeof result.confidence === 'number') {
    result.confidence = Math.min(1, Math.max(0, result.confidence))
  }
  return result
}

/** @returns {'sk-ant-'|'sk-'|'g2a_'|null} */
function detectKeyPrefixHint(text) {
  const t = String(text || '')
  if (!t) return null
  if (
    /sk-ant-[\s_-]*前缀|前缀[\s\S]{0,10}sk-ant-|prefix[\s:：=]*sk-ant-|(?:加|补|带|加上|补上)[\s\S]{0,8}sk-ant-/i.test(
      t,
    )
  ) {
    return 'sk-ant-'
  }
  if (/g2a_[\s_-]*前缀|前缀[\s\S]{0,10}g2a_|prefix[\s:：=]*g2a_/i.test(t)) return 'g2a_'
  if (
    /(?:别忘了|记得|需要|请|务必|别漏)[\s\S]{0,20}sk-[\s_-]*前缀|sk-[\s_-]*前缀|前缀[\s\S]{0,10}sk-(?!ant)|prefix[\s:：=]*sk-(?!ant)|(?:加|补|带|加上|补上)[\s\S]{0,6}sk-(?!ant)/i.test(
      t,
    )
  ) {
    return 'sk-'
  }
  return null
}

function applyKeyPrefixHints(key, text) {
  if (!key) return key
  let k = String(key).trim()
  if (!k) return k
  if (KEY_PREFIX_BODY_RE.test(k)) {
    return sanitizeApiKey(k.replace(/^Bearer\s*/i, ''))
  }
  const prefix = detectKeyPrefixHint(text)
  if (!prefix) return k
  if (k.length < 8 || k.length > 512) return k
  if (!/^[A-Za-z0-9_+\-./]+$/.test(k) || /^https?:\/\//i.test(k)) return k
  return prefix + k
}

/**
 * @param {string} text
 */
function looksLikeConfig(text) {
  if (!text || text.trim().length < MIN_SELECTION_LEN) return false
  let t = repairBrokenBase64(normalizeShareText(text))
  if (t.length > MAX_SELECTION_LEN) t = t.slice(0, MAX_SELECTION_LEN)
  if (DEEPLINK_RE.test(t)) return true
  if (/ANTHROPIC_|OPENAI_|CODEX_|BASE_URL|API_KEY|apiKey|baseUrl|endpoint|Base\s*URL/i.test(t))
    return true
  if (/sk-ant-|sk-[A-Za-z0-9]{16,}/.test(t)) return true
  if (/https?:\/\//i.test(t) && /sk-|Bearer\s+/i.test(t)) return true
  // labeled shares: url： / key： / 密钥： / API Key（...）
  if (
    /(?:url|base[_-]?url|base\s*url|endpoint|key|api[_-]?key|api\s*key|token|密钥|地址|接口)/i.test(
      t,
    )
  ) {
    if (/https?:\/\//i.test(t) || /[A-Za-z0-9_+\-/]{16,}/.test(t)) return true
  }
  // url + base64-ish token (key often base64-encoded on linux.do)
  if (/https?:\/\//i.test(t) && /[A-Za-z0-9+/]{32,}={0,2}/.test(t)) return true
  // standalone base64 only if it decodes to a key or config-shaped text (avoid AAAA… noise)
  if (hasUsefulBase64Blob(t)) return true
  if (/\{[\s\S]*"(?:apiKey|api_key|baseUrl|endpoint|base_url)"[\s\S]*\}/.test(t)) return true
  return false
}

/**
 * True when a base64-ish token decodes to an API key or config-like payload.
 * Prevents long random A-Z runs from lighting the import button.
 * @param {string} text
 */
function hasUsefulBase64Blob(text) {
  const re = new RegExp(`${B64_BOUNDARY_L}([A-Za-z0-9+/]{40,}={0,2})${B64_BOUNDARY_R}`, 'g')
  let m
  while ((m = re.exec(text)) !== null) {
    const token = m[1]
    if (token.startsWith('sk-') || token.startsWith('http')) continue
    try {
      const decoded = base64Decode(token).trim()
      if (!decoded || decoded.length < 8) continue
      const ascii = decoded.replace(/[^\x20-\x7E]/g, '').replace(/\s+/g, '')
      if (KEY_PREFIX_RE.test(ascii) && ascii.length >= 8 && ascii.length <= 512) {
        return true
      }
      if (
        /[{=\n:]/.test(decoded) &&
        (/https?:\/\//.test(decoded) || /API|KEY|BASE|endpoint|baseUrl/i.test(decoded))
      ) {
        return true
      }
    } catch {
      /* ignore */
    }
  }
  return false
}

/**
 * @param {ParseResult} result
 * @param {AppKind} [appOverride]
 * @param {object} [modelInfo] - Optional model extraction result
 * @returns {string}
 */
function buildDeeplink(result, appOverride, modelInfo) {
  const app = appOverride || result.app
  if (!app) {
    throw new Error('app is required (claude or codex)')
  }

  const params = new URLSearchParams()
  params.set('resource', 'provider')
  params.set('app', app)
  params.set('name', result.name || defaultName())

  if (result.endpoint) params.set('endpoint', result.endpoint)
  if (result.apiKey) params.set('apiKey', result.apiKey)

  if (result.config) {
    params.set('config', base64Encode(result.config))
    params.set('configFormat', result.configFormat || 'json')
  }

  // Add model parameters when available
  if (modelInfo) {
    if (modelInfo.model) params.set('model', modelInfo.model)
    if (app === 'claude') {
      if (modelInfo.haikuModel) params.set('haikuModel', modelInfo.haikuModel)
      if (modelInfo.sonnetModel) params.set('sonnetModel', modelInfo.sonnetModel)
      if (modelInfo.opusModel) params.set('opusModel', modelInfo.opusModel)
    }
  }

  // URLSearchParams encodes spaces as +, deep links often prefer %20 — fine for most handlers
  return `ccswitch://v1/import?${params.toString()}`
}

/**
 * @param {string} key
 * @returns {string}
 */
function maskKey(key) {
  if (!key) return ''
  if (key.length <= 12) return '*'.repeat(Math.min(key.length, 8))
  return `${key.slice(0, 8)}****${key.slice(-4)}`
}

/**
 * Classify target app from strong provider signals only.
 * Model lists (gpt/claude/grok mixed on relay shares) are stripped so they
 * do not push codex/claude; ambiguous → null (user picks).
 *
 * @param {string} text
 * @param {object} fields
 * @returns {AppKind}
 */
function classifyApp(text, fields = {}) {
  const key = String(fields.apiKey || '').toLowerCase()
  const endpoint = String(fields.endpoint || '').toLowerCase()
  const name = String(fields.name || '').toLowerCase()
  const config = String(fields.config || '').toLowerCase()
  // Free text without model-id noise (relay posts list many models)
  const prose = stripModelTokens(String(text || '').toLowerCase())
  const blob = [prose, endpoint, key, name, config].join('\n')

  let claude = 0
  let codex = 0

  if (/sk-ant-/.test(key) || /sk-ant-/.test(blob)) claude += 3
  if (/anthropic/.test(blob)) claude += 2
  if (/anthropic_|claude_base|claude_api/.test(blob)) claude += 2

  if (/openai/.test(blob)) codex += 2
  if (/\bcodex\b/.test(blob)) codex += 3
  if (/openai_api_key|openai_base|codex_api|codex_base/.test(blob)) codex += 2
  if (/api\.openai\.com/.test(endpoint) || /api\.openai\.com/.test(blob)) codex += 2

  // Bare sk- is too common on multi-protocol relays — only nudge codex when
  // endpoint/name already looks OpenAI-ish.
  if (/^sk-(?!ant)/i.test(key) && claude < 2) {
    if (/openai|codex/.test(endpoint) || /openai|codex/.test(name)) codex += 0.5
  }

  if (claude === 0 && codex === 0) return null
  // Require a clear margin; ties and near-ties → user picks
  if (claude >= codex + 0.5) return 'claude'
  if (codex >= claude + 0.5) return 'codex'
  return null
}

/**
 * Remove model id tokens so "gpt-5.5，claude系列，grok4.5" does not classify app.
 * @param {string} s
 */
function stripModelTokens(s) {
  return String(s || '')
    .replace(/claude[-_.\s]?\w[\w.-]*/gi, ' ')
    .replace(/gpt[-_.\s]?\w[\w.-]*/gi, ' ')
    .replace(/grok[-_.\s]?\w[\w.-]*/gi, ' ')
    .replace(/gemini[-_.\s]?\w[\w.-]*/gi, ' ')
    .replace(/deepseek[-_.\s]?\w[\w.-]*/gi, ' ')
    .replace(/\bo[13](?:-mini|-preview)?\b/gi, ' ')
}

/**
 * Switch result to another endpoint/apiKey candidate pair (from mixed multi-match).
 * @param {ParseResult} result
 * @param {number} index
 * @returns {ParseResult}
 */
function selectCandidate(result, index) {
  if (!result) return result
  const list = result.candidates
  if (!list || list.length === 0) return result
  const i = Math.max(0, Math.min(Number(index) || 0, list.length - 1))
  const pair = list[i]
  const next = {
    ...result,
    endpoint: pair.endpoint,
    apiKey: pair.apiKey,
    candidateIndex: i,
    candidateCount: list.length,
  }
  next.warnings = buildWarnings(next)
  next.confidence = scoreFields(next, next.app)
  if (typeof next.confidence === 'number') {
    next.confidence = Math.min(1, Math.max(0, next.confidence))
  }
  return next
}

// ─── internals ───────────────────────────────────────────────

function defaultName() {
  const d = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return `linuxdo-${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`
}

function stripMarkdownFences(text) {
  return text
    .replace(/^```[a-zA-Z0-9]*\s*\n?/gm, '')
    .replace(/```$/gm, '')
    .trim()
}

function emptyResult(partial) {
  return {
    name: defaultName(),
    app: null,
    endpoint: null,
    apiKey: null,
    config: null,
    configFormat: null,
    source: 'mixed',
    confidence: 0,
    candidateCount: 1,
    candidateIndex: 0,
    candidates: [],
    warnings: [],
    deeplink: null,
    ...partial,
  }
}

function extractDeeplink(text) {
  const m = text.match(DEEPLINK_RE)
  return m ? m[0] : null
}

/**
 * @param {string} link
 * @returns {ParseResult|null}
 */
function parseDeeplink(link) {
  try {
    // Only provider imports — never rewrite mcp/prompt/skill into provider.
    // Manual parse: URL() may not like custom schemes in all envs.
    const raw = String(link || '').trim()
    if (!/^ccswitch:/i.test(raw)) return null
    // Accept ccswitch://v1/import?... or ccswitch:v1/import?...
    const pathPart = raw.replace(/^ccswitch:\/\//i, '').replace(/^ccswitch:/i, '')
    const qIndex = pathPart.indexOf('?')
    if (qIndex < 0) return null
    const path = pathPart.slice(0, qIndex).replace(/\/+$/, '')
    if (!/^v1\/import$/i.test(path)) return null
    const qs = pathPart.slice(qIndex + 1)
    const params = new URLSearchParams(qs)
    const resource = params.get('resource')
    if (resource !== 'provider') return null
    const app = normalizeApp(params.get('app'))
    const name = params.get('name') || defaultName()
    const endpoint = params.get('endpoint') || params.get('baseUrl') || null
    const apiKey = params.get('apiKey') || params.get('api_key') || null
    let config = null
    let configFormat = null
    const configB64 = params.get('config')
    if (configB64) {
      try {
        config = base64Decode(configB64)
        configFormat = /** @type {'json'|'toml'} */ (params.get('configFormat') || 'json')
      } catch {
        /* ignore */
      }
    }
    const confidence = endpoint || apiKey || config ? 0.95 : 0.5
    if (!endpoint && !apiKey && !config) return null
    return emptyResult({
      name,
      app,
      endpoint,
      apiKey,
      config,
      configFormat,
      source: 'deeplink',
      confidence,
    })
  } catch {
    return null
  }
}

function normalizeApp(app) {
  if (!app) return null
  const a = String(app).toLowerCase()
  if (a === 'claude' || a === 'claudecode' || a === 'claude-code') return 'claude'
  if (a === 'codex') return 'codex'
  return null
}

function tryParseBase64(text) {
  BASE64_RE.lastIndex = 0
  let best = null
  let m
  while ((m = BASE64_RE.exec(text)) !== null) {
    const token = m[1]
    if (token.length < 40) continue
    // skip if looks like a normal url fragment or key
    if (token.startsWith('sk-')) continue
    let decoded
    try {
      decoded = base64Decode(token)
    } catch {
      continue
    }
    if (!decoded || decoded.length < 10) continue
    // must look like text config
    if (!/[{=\n:]/.test(decoded) && !/https?:\/\//.test(decoded) && !/API|KEY|BASE/i.test(decoded)) {
      continue
    }
    // parse decoded without re-running base64 on itself forever
    const inner =
      tryParseJson(decoded) ||
      tryParseTomlLike(decoded) ||
      tryParseEnv(decoded) ||
      tryParseMixed(decoded)
    if (inner && (inner.endpoint || inner.apiKey || inner.config)) {
      inner.source = 'base64'
      inner.confidence = Math.min(1, (inner.confidence || 0.6) + 0.1)
      if (!best || inner.confidence > best.confidence) best = inner
    }
  }
  return best
}

function tryParseJson(text) {
  const objects = extractJsonObjects(text)
  let best = null
  for (const objStr of objects) {
    let obj
    try {
      obj = JSON.parse(objStr)
    } catch {
      continue
    }
    if (!obj || typeof obj !== 'object' || Array.isArray(obj)) continue
    const fields = pickProviderFields(obj)
    if (!fields.endpoint && !fields.apiKey && !fields.hasConfigShape) continue
    // Discourse may turn "url" value into bare link text "url" — recover real https from surrounding text
    if (!fields.endpoint) {
      const urls = unique(matchAll(text, URL_RE).map(cleanUrl)).filter((u) => isHttpUrl(u))
      const recovered = pickBestUrl(urls, text)
      if (recovered) fields.endpoint = recovered
    }
    const app = classifyApp(text, fields)
    const r = emptyResult({
      name: fields.name || defaultName(),
      app,
      endpoint: fields.endpoint,
      apiKey: fields.apiKey,
      config: fields.hasConfigShape ? objStr : null,
      configFormat: fields.hasConfigShape ? 'json' : null,
      source: 'json',
      confidence: scoreFields(fields, app),
      warnings: buildWarnings(fields),
    })
    if (!best || r.confidence > best.confidence) best = r
  }

  // Broken / partial JSON (smart quotes, missing braces): still pull "key"/"url" string fields
  if (!best || (!best.apiKey && !best.endpoint)) {
    const loose = extractJsonishFields(text)
    if (loose.hit && (loose.endpoint || loose.apiKey)) {
      const fields = {
        name: loose.name || defaultName(),
        endpoint: loose.endpoint,
        apiKey: loose.apiKey,
      }
      const app = classifyApp(text, fields)
      const r = emptyResult({
        name: fields.name,
        app,
        endpoint: fields.endpoint,
        apiKey: fields.apiKey,
        source: 'json',
        confidence: scoreFields(fields, app) * 0.95,
        warnings: buildWarnings(fields),
      })
      if (!best || r.confidence > best.confidence) best = r
    }
  }
  return best
}

/**
 * Regex fallback for provider-like JSON when JSON.parse fails (newapi_channel_conn shares, etc.).
 * Only fires when quoted JSON field names are present — never steal plain env/mixed shares.
 * Tolerates newlines after `:` and unquoted http(s) url values (Discourse linkify).
 * @param {string} text
 */
function extractJsonishFields(text) {
  const result = { endpoint: null, apiKey: null, name: null, hit: false }

  // Must look like JSON-ish (brace + quoted key) before we try loose extraction
  if (!/\{[\s\S]*["'](?:key|apiKey|api_key|url|baseUrl|base_url|endpoint)["']\s*:/i.test(text)) {
    return result
  }

  // "url": "https://..." OR "url":\nhttps://... (unquoted after Discourse linkify)
  const urlField = text.match(
    /["'](?:url|baseUrl|base_url|endpoint|api_base)["']\s*:\s*(?:["'](https?:\/\/[^"']+)["']|(https?:\/\/[^\s"'`<>，。；、}\]]+))/i,
  )
  if (urlField) {
    result.endpoint = cleanUrl(urlField[1] || urlField[2])
    result.hit = true
  }

  // "key": "c2st..." allowing newline between colon and value
  const keyField = text.match(
    /["'](?:key|apiKey|api_key|token|secret|auth_token)["']\s*:\s*["']?\s*([A-Za-z0-9+/_-]{16,}={0,2})["']?/i,
  )
  if (keyField) {
    result.apiKey = maybeDecodeKey(keyField[1])
    result.hit = true
  }

  const nameField = text.match(/["'](?:name|title|provider|_type|type)["']\s*:\s*["']([^"']+)["']/i)
  if (nameField) result.name = nameField[1]

  // Only recover free-floating https when we already hit a JSON key field
  // (Discourse may have turned the url value into bare link text "url")
  if (result.hit && !result.endpoint) {
    const urls = unique(matchAll(text, URL_RE).map(cleanUrl)).filter((u) => isHttpUrl(u))
    result.endpoint = pickBestUrl(urls, text)
  }
  return result
}

function extractJsonObjects(text) {
  const results = []
  const limit = Math.min(text.length, MAX_SELECTION_LEN)
  for (let i = 0; i < limit; i++) {
    if (text[i] !== '{') continue
    if (results.length >= MAX_JSON_OBJECTS) break
    let depth = 0
    let inStr = false
    let esc = false
    // Cap scan window per brace so pathological unclosed `{` runs stay linear-ish
    const end = Math.min(limit, i + MAX_DECODED_LEN)
    for (let j = i; j < end; j++) {
      const c = text[j]
      if (inStr) {
        if (esc) {
          esc = false
        } else if (c === '\\') {
          esc = true
        } else if (c === '"') {
          inStr = false
        }
        continue
      }
      if (c === '"') {
        inStr = true
        continue
      }
      if (c === '{') depth++
      else if (c === '}') {
        depth--
        if (depth === 0) {
          results.push(text.slice(i, j + 1))
          i = j
          break
        }
      }
    }
  }
  return results
}

function isHttpUrl(value) {
  return typeof value === 'string' && /^https?:\/\//i.test(value.trim())
}

function pickProviderFields(obj) {
  const name = firstString(obj, ['name', 'title', 'label', 'provider', 'providerName', '_type', 'type'])
  let endpoint = firstString(obj, [
    'endpoint',
    'baseUrl',
    'base_url',
    'baseURL',
    'api_base',
    'apiBase',
    'url',
    'host',
  ])
  // Discourse may turn JSON "url" value into visible link text "url" — not a real endpoint
  if (endpoint && !isHttpUrl(endpoint)) endpoint = null

  const apiKey = firstString(obj, [
    'apiKey',
    'api_key',
    'key',
    'token',
    'authToken',
    'auth_token',
    'secret',
    'access_token',
  ])
  // nested env style
  const env = obj.env || obj.environment || obj.settings || null
  let ep = endpoint
  let key = apiKey
  if (env && typeof env === 'object') {
    ep = ep || firstString(env, ENV_URL_KEYS.map((k) => k).concat(['baseUrl', 'endpoint']))
    if (ep && !isHttpUrl(ep)) ep = null
    // also case-insensitive scan
    if (!ep) ep = scanObjectForUrl(env)
    if (!key) key = firstString(env, ENV_KEY_KEYS.concat(['apiKey', 'key']))
    if (!key) key = scanObjectForKey(env)
  }
  if (!ep) ep = scanObjectForUrl(obj)
  if (!key) key = scanObjectForKey(obj)

  // Only attach raw JSON as config for full provider/app configs.
  // Simple {url,key,name} / newapi shares must not smuggle hidden fields into the deeplink.
  const hasConfigShape = isFullProviderConfig(obj, ep, key)
  return { name, endpoint: ep, apiKey: key, hasConfigShape }
}

/**
 * True when obj looks like a full Claude/Codex provider config (env block, usage script, …),
 * not a minimal share object with only url/key/name.
 * @param {object} obj
 * @param {string|null} ep
 * @param {string|null} key
 */
function isFullProviderConfig(obj, ep, key) {
  if (!obj || typeof obj !== 'object') return false
  if (!ep && !key) return false
  if (obj.usageScript || obj.usageAccessToken || obj.usage_script) return true
  const env = obj.env || obj.environment
  if (env && typeof env === 'object' && !Array.isArray(env)) {
    const envKeys = Object.keys(env)
    if (envKeys.some((k) => /ANTHROPIC|OPENAI|CODEX|BASE_URL|API_KEY|AUTH_TOKEN/i.test(k))) {
      return true
    }
    if (envKeys.length >= 3) return true
  }
  if (obj.settings && typeof obj.settings === 'object' && !Array.isArray(obj.settings)) {
    if (Object.keys(obj.settings).length >= 3) return true
  }
  // Nested models / transformers / custom headers etc. beyond the simple share shape
  const simple = new Set([
    'name',
    'title',
    'label',
    'provider',
    'providername',
    '_type',
    'type',
    'endpoint',
    'baseurl',
    'base_url',
    'baseurl',
    'api_base',
    'apibase',
    'url',
    'host',
    'apikey',
    'api_key',
    'key',
    'token',
    'authtoken',
    'auth_token',
    'secret',
    'access_token',
  ])
  const extras = Object.keys(obj).filter((k) => !simple.has(k.toLowerCase()))
  return extras.length >= 2
}

function firstString(obj, keys) {
  for (const k of keys) {
    if (obj[k] != null && String(obj[k]).trim()) return String(obj[k]).trim()
  }
  // case-insensitive
  const lowerMap = {}
  for (const [k, v] of Object.entries(obj)) {
    lowerMap[k.toLowerCase()] = v
  }
  for (const k of keys) {
    const v = lowerMap[k.toLowerCase()]
    if (v != null && String(v).trim()) return String(v).trim()
  }
  return null
}

function scanObjectForUrl(obj) {
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === 'string' && /^https?:\/\//i.test(v.trim())) {
      if (/url|base|endpoint|host|api/i.test(k)) return v.trim()
    }
  }
  for (const v of Object.values(obj)) {
    if (typeof v === 'string' && /^https?:\/\//i.test(v.trim())) return v.trim()
  }
  return null
}

function scanObjectForKey(obj) {
  // Exact field names only — avoid matching monkey_token / description etc.
  const exact = new Set([
    'apikey',
    'api_key',
    'key',
    'token',
    'authtoken',
    'auth_token',
    'secret',
    'access_token',
    'authorization',
  ])
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === 'string' && exact.has(String(k).toLowerCase()) && v.trim().length >= 8) {
      return v.trim()
    }
  }
  for (const v of Object.values(obj)) {
    if (typeof v === 'string' && KEY_PREFIX_BODY_RE.test(v.trim())) {
      return sanitizeApiKey(v.trim().replace(/^Bearer\s+/i, ''))
    }
  }
  return null
}

function tryParseTomlLike(text) {
  const endpoint =
    matchQuotedAssignment(text, ['base_url', 'baseUrl', 'endpoint', 'api_base', 'url']) || null
  const apiKey =
    matchQuotedAssignment(text, ['api_key', 'apiKey', 'key', 'token', 'auth_token', 'secret']) || null
  if (!endpoint && !apiKey) return null
  // require at least one assignment-style line to distinguish from mixed
  if (!/^\s*[\w.]+\s*=\s*.+/m.test(text) && !endpoint) return null
  if (!/=\s*["']?/.test(text)) return null

  const name = matchQuotedAssignment(text, ['name', 'title']) || defaultName()
  const fields = { name, endpoint, apiKey }
  const app = classifyApp(text, fields)
  return emptyResult({
    name,
    app,
    endpoint,
    apiKey,
    source: 'toml',
    confidence: scoreFields(fields, app),
    warnings: buildWarnings(fields),
  })
}

function matchQuotedAssignment(text, keys) {
  for (const key of keys) {
    const re = new RegExp(
      `(?:^|[\\s;])${escapeRegExp(key)}\\s*=\\s*(?:"([^"]+)"|'([^']+)'|(\\S+))`,
      'im',
    )
    const m = text.match(re)
    if (m) return (m[1] || m[2] || m[3] || '').trim()
  }
  return null
}

function tryParseEnv(text) {
  const map = parseEnvMap(text)
  if (Object.keys(map).length === 0) return null

  let endpoint = null
  let apiKey = null
  for (const k of ENV_URL_KEYS) {
    if (map[k]) {
      endpoint = map[k]
      break
    }
  }
  for (const k of ENV_KEY_KEYS) {
    if (map[k]) {
      apiKey = map[k]
      break
    }
  }
  // fuzzy
  if (!endpoint) {
    for (const [k, v] of Object.entries(map)) {
      if (/BASE_URL|API_BASE|ENDPOINT/i.test(k) && /^https?:\/\//i.test(v)) {
        endpoint = v
        break
      }
    }
  }
  if (!apiKey) {
    for (const [k, v] of Object.entries(map)) {
      if (/API_KEY|AUTH_TOKEN|TOKEN|SECRET/i.test(k) && v.length >= 8) {
        apiKey = v
        break
      }
    }
  }

  if (!endpoint && !apiKey) return null

  const fields = { name: defaultName(), endpoint, apiKey }
  const app = classifyApp(text, fields)
  return emptyResult({
    name: defaultName(),
    app,
    endpoint,
    apiKey,
    source: 'env',
    confidence: scoreFields(fields, app) + 0.05,
    warnings: buildWarnings(fields),
  })
}

function parseEnvMap(text) {
  const map = {}
  const lines = text.split(/\r?\n/)
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    // KEY=value or export KEY=value
    const m = trimmed.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/)
    if (!m) continue
    let val = m[2].trim()
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1)
    }
    // strip trailing inline comments loosely
    val = val.replace(/\s+#.*$/, '').trim()
    if (val) map[m[1]] = val
  }
  // also allow single-line KEY=value KEY2=value
  if (Object.keys(map).length === 0) {
    const re = /([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^\s]+)/g
    let m
    while ((m = re.exec(text)) !== null) {
      if (ENV_URL_KEYS.includes(m[1]) || ENV_KEY_KEYS.includes(m[1]) || /URL|KEY|TOKEN/i.test(m[1])) {
        map[m[1]] = m[2].replace(/^["']|["']$/g, '')
      }
    }
  }
  return map
}

function tryParseMixed(text) {
  const labeled = extractLabeledFields(text)

  const urls = unique([
    ...matchAll(text, URL_RE).map(cleanUrl),
    ...(labeled.endpoint ? [labeled.endpoint] : []),
  ])
    .filter((u) => isHttpUrl(u))
    .slice(0, MAX_URLS)

  const keys = unique([
    ...matchAll(text, SK_ANT_RE),
    ...matchAll(text, SK_RE),
    ...matchAllGroups(text, BEARER_RE, 1),
    ...extractLooseKeys(text),
    ...extractBase64DecodedKeys(text),
    ...(labeled.apiKey ? [labeled.apiKey] : []),
  ]).map((k) => maybeDecodeKey(k))

  const apiKeys = unique(keys).slice(0, MAX_KEYS)

  if (urls.length === 0 && apiKeys.length === 0) return null

  const candidates = buildCandidatePairs(urls, apiKeys, text, labeled)
  if (candidates.length === 0) return null

  const best = candidates[0]
  let endpoint = best.endpoint
  let apiKey = best.apiKey

  const fields = { name: labeled.name || defaultName(), endpoint, apiKey }
  const app = classifyApp(text, fields)
  const candidateCount = candidates.length
  const warnings = buildWarnings(fields)
  if (candidateCount > 1) {
    warnings.push(
      `检测到 ${urls.length} 个 URL、${apiKeys.length} 个 key，共 ${candidateCount} 组候选（可在确认卡切换）`,
    )
  }

  const confidence = scoreFields(fields, app) * (candidateCount > 1 ? 0.9 : 1)
  if (!endpoint && !apiKey) return null

  return emptyResult({
    name: fields.name,
    app,
    endpoint,
    apiKey,
    source: 'mixed',
    confidence: labeled.hit ? Math.min(1, confidence + 0.1) : confidence,
    candidateCount,
    candidateIndex: 0,
    candidates,
    warnings,
  })
}

/**
 * Rank endpoint×key pairs for mixed shares. Labeled fields pin when present.
 * @param {string[]} urls
 * @param {string[]} apiKeys
 * @param {string} text
 * @param {{ endpoint?: string|null, apiKey?: string|null }} labeled
 * @returns {CandidatePair[]}
 */
function buildCandidatePairs(urls, apiKeys, text, labeled) {
  const preferredUrl = labeled.endpoint || pickBestUrl(urls, text)
  const preferredKey = labeled.apiKey ? decodeKeyBody(labeled.apiKey) : pickBestKey(apiKeys)

  /** @type {CandidatePair[]} */
  const pairs = []
  const seen = new Set()
  const add = (endpoint, apiKey) => {
    if (pairs.length >= MAX_CANDIDATES) return false
    const id = `${endpoint || ''}\0${apiKey || ''}`
    if (seen.has(id)) return true
    seen.add(id)
    pairs.push({ endpoint: endpoint || null, apiKey: apiKey || null })
    return pairs.length < MAX_CANDIDATES
  }

  // Preferred pair first (labeled / best-scored)
  if (urls.length && apiKeys.length) {
    add(preferredUrl || urls[0], preferredKey || apiKeys[0])
    // Zip by index — same-paragraph shares often list urlN/keyN in order
    const n = Math.max(urls.length, apiKeys.length)
    for (let i = 0; i < n && pairs.length < MAX_CANDIDATES; i++) {
      add(urls[i] || preferredUrl || urls[0], apiKeys[i] || preferredKey || apiKeys[0])
    }
    // Remaining limited cartesian (already capped by MAX_URLS × MAX_KEYS)
    outer: for (const u of urls) {
      for (const k of apiKeys) {
        if (!add(u, k)) break outer
      }
    }
  } else if (urls.length === 0) {
    for (const k of apiKeys) {
      if (!add(null, k)) break
    }
  } else {
    for (const u of urls) {
      if (!add(u, null)) break
    }
  }

  pairs.sort((a, b) => {
    const sa = scorePair(a, preferredUrl, preferredKey, text)
    const sb = scorePair(b, preferredUrl, preferredKey, text)
    return sb - sa
  })

  return pairs.slice(0, MAX_CANDIDATES)
}

/**
 * @param {CandidatePair} pair
 * @param {string|null} preferredUrl
 * @param {string|null} preferredKey
 * @param {string} text
 */
function scorePair(pair, preferredUrl, preferredKey, text) {
  let s = 0
  if (pair.endpoint && pair.apiKey) s += 2
  if (preferredUrl && pair.endpoint === preferredUrl) s += 3
  if (preferredKey && pair.apiKey === preferredKey) s += 3
  if (pair.endpoint) {
    const lower = pair.endpoint.toLowerCase()
    if (/api\.|anthropic|openai|proxy|relay/.test(lower)) s += 1
    // demote billing / docs / dashboard style URLs
    if (/usage|billing|dashboard|docs\.|status\.|github\.com|linux\.do/.test(lower)) s -= 2
  }
  if (pair.apiKey) {
    if (pair.apiKey.startsWith('sk-ant-')) s += 2
    else if (pair.apiKey.startsWith('sk-')) s += 1
    else if (/^(?:g2a_|tp-)/i.test(pair.apiKey)) s += 1
  }
  // slight preference for shorter path endpoints (often the real base)
  if (pair.endpoint) {
    try {
      const path = new URL(pair.endpoint).pathname || '/'
      if (path === '/' || path === '/v1' || path === '/v1/') s += 0.5
    } catch {
      /* ignore */
    }
  }
  void text
  return s
}

// Shared label matchers (one source of truth for table / colon / glued forms)
const LABEL_KEY_RE =
  /^(?:api\s*key|api[_-]?key|key|token|secret|auth[_-]?token|密钥)(?:\b|[（(]|$)/i
const LABEL_URL_RE =
  /^(?:url|base\s*url|base[_-]?url|endpoint|api\s*base|api[_-]?base|host|地址|接口|链接)(?:\b|[（(]|$)/i
const LABEL_NAME_RE = /^(?:name|名称|名字)(?:\b|[（(]|$)/i
const LABEL_ANY_RE =
  /^(url|base\s*url|base[_-]?url|endpoint|api\s*base|api[_-]?base|host|地址|接口|链接|key|api\s*key|api[_-]?key|token|secret|auth[_-]?token|密钥|name|名称|名字)/i
const LABEL_KEY_PREFIX_RE =
  /^(?:api\s*key|api[_-]?key|key|token|secret|auth[_-]?token|密钥)(?:\s*[（(][^）)]*[）)])?\s*[:：]?\s*/i

function labelKind(label) {
  const s = String(label || '').toLowerCase().replace(/\s+/g, '')
  if (/url|base|endpoint|host|地址|接口|链接/.test(s)) return 'url'
  if (/key|token|secret|auth|密钥/.test(s)) return 'key'
  if (/name|名称|名字/.test(s)) return 'name'
  return null
}

function stripLabeledValue(value) {
  let v = String(value || '').trim()
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    v = v.slice(1, -1).trim()
  }
  return v.replace(/[，。；、！？]+$/g, '')
}

function lookLikeKeyValue(v) {
  return (
    !!v &&
    (KEY_PREFIX_BODY_RE.test(v) ||
      /^[A-Za-z0-9+/_-]{16,}={0,2}$/.test(v) ||
      v.length >= 12)
  )
}

function assignLabeledField(result, kind, value) {
  if (!kind || value == null || value === '') return
  if (kind === 'url') {
    const u = (String(value).match(URL_RE) || [])[0]
    if (u) result.endpoint = cleanUrl(u)
    else if (/^https?:\/\//i.test(value)) result.endpoint = cleanUrl(value)
    else return
  } else if (kind === 'key') {
    // raw token — finalizeResult runs normalizeApiKey once
    result.apiKey = String(value).replace(/\s+/g, '')
  } else if (kind === 'name') {
    result.name = String(value).trim()
  }
  result.hit = true
}

function joinBase64Continuations(lines, from, start, hardCap) {
  let next = start
  let k = from
  while (k < hardCap && /^[A-Za-z0-9+/_-]{8,}={0,2}$/.test(lines[k].trim())) {
    next += lines[k].trim()
    k++
  }
  return next.replace(/\s+/g, '')
}

function readFollowingKey(lines, afterIdx) {
  for (let j = afterIdx; j < Math.min(afterIdx + 4, lines.length); j++) {
    let next = lines[j].trim()
    if (!next) continue
    if (LABEL_URL_RE.test(next) || LABEL_KEY_RE.test(next) || LABEL_NAME_RE.test(next)) break
    next = next.replace(LABEL_KEY_PREFIX_RE, '')
    next = joinBase64Continuations(lines, j + 1, next, Math.min(afterIdx + 5, lines.length))
    if (lookLikeKeyValue(next) && !/^https?:\/\//i.test(next)) return next
  }
  return null
}

/**
 * Labeled / table shares. Stores raw key tokens; normalizeApiKey in finalizeResult.
 */
function extractLabeledFields(text) {
  const result = { endpoint: null, apiKey: null, name: null, hit: false }
  const lines = text.split(/\r?\n/)

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()
    if (!line) continue

    const keyGlued = line.match(
      new RegExp(LABEL_KEY_PREFIX_RE.source + '([A-Za-z0-9+/_-]{16,}={0,2})\s*$', 'i'),
    )
    if (keyGlued && !result.apiKey) {
      assignLabeledField(result, 'key', keyGlued[1])
      continue
    }

    if (new RegExp(LABEL_KEY_PREFIX_RE.source + '$', 'i').test(line) && !result.apiKey) {
      const v = readFollowingKey(lines, i + 1)
      if (v) assignLabeledField(result, 'key', v)
      continue
    }

    const labeled = line.match(
      new RegExp(LABEL_ANY_RE.source + '\s*(?:[:：=]\s*|\s{2,})(.+)$', 'i'),
    )
    if (labeled) {
      const kind = labelKind(labeled[1])
      let value = stripLabeledValue(labeled[2])
      if (kind === 'key' && (!lookLikeKeyValue(value) || /base64|解码|自行/i.test(value))) {
        value = readFollowingKey(lines, i + 1) || value
      }
      if (value && !(kind === 'key' && /base64|解码|自行/i.test(value) && !lookLikeKeyValue(value))) {
        assignLabeledField(result, kind, value)
      }
      continue
    }
  }

  if (!result.endpoint) {
    const m = text.match(
      /(?:url|base[_-]?url|base\s*url|endpoint|地址|接口)\s*[:：]\s*(https?:\/\/[^\s，。；]+)/i,
    )
    if (m) assignLabeledField(result, 'url', m[1])
  }
  if (!result.apiKey) {
    const m = text.match(
      /(?:key|api[_-]?key|api\s*key|token|密钥)\s*[:：]\s*([A-Za-z0-9_+\-/=]{8,})/i,
    )
    if (m) assignLabeledField(result, 'key', m[1])
  }

  return result
}

/**
 * Decode b64/hex + strip CJK watermark; no prefix hints.
 * Supports nested base64 (e.g. "\u4FE9\u6B21base64" \u2192 outer b64 \u2192 inner b64 \u2192 sk-\u2026).
 * Caps depth so random blobs do not loop forever.
 */
function decodeKeyBody(value) {
  if (!value) return value
  let v = String(value)
    .replace(/[\u200B-\u200D\uFEFF\u00AD\u2060]/g, '')
    .replace(/[\s\u00A0]+/g, '')
    .trim()
  if (KEY_PREFIX_BODY_RE.test(v)) {
    return sanitizeApiKey(v.replace(/^Bearer\s*/i, ''))
  }

  // Hex first (even length long enough)
  if (/^[0-9a-fA-F]{24,}$/.test(v) && v.length % 2 === 0) {
    try {
      const decoded = sanitizeApiKey(hexDecode(v).trim())
      if (isDecodableKeyBody(decoded) && (hasKeyPrefix(decoded) || decoded.length < v.length)) {
        return peelBase64Layers(decoded)
      }
    } catch {
      /* base64 next */
    }
  }

  return peelBase64Layers(v)
}

/** Peel nested base64 (e.g. 俩次base64) until sk-/g2a_/tp- or layers stop. */
function peelBase64Layers(value, maxDepth = 4) {
  let v = String(value || '').trim()
  if (!v) return v
  if (hasKeyPrefix(v)) return sanitizeApiKey(v)

  for (let depth = 0; depth < maxDepth; depth++) {
    if (!/^[A-Za-z0-9+/_-]+={0,2}$/.test(v) || v.length < 16) break
    let decoded
    try {
      decoded = base64Decode(v).trim()
    } catch {
      break
    }
    if (!decoded || decoded === v) break
    const cleaned = sanitizeApiKey(decoded)
    if (hasKeyPrefix(cleaned) && isDecodableKeyBody(cleaned)) {
      return cleaned
    }
    // Intermediate pure base64 → peel again
    if (
      isDecodableKeyBody(cleaned) &&
      /^[A-Za-z0-9+/_-]+={0,2}$/.test(cleaned) &&
      cleaned.length >= 16 &&
      cleaned.length < v.length
    ) {
      v = cleaned
      continue
    }
    if (isDecodableKeyBody(cleaned) && (cleaned.includes('_') || cleaned.length < v.length)) {
      return cleaned
    }
    break
  }
  return v
}
function maybeDecodeKey(value) {
  return decodeKeyBody(value)
}

function hasKeyPrefix(s) {
  return KEY_PREFIX_RE.test(s)
}

function isDecodableKeyBody(decoded) {
  return (
    !!decoded &&
    decoded.length >= 8 &&
    decoded.length <= 512 &&
    /^[\x20-\x7E]+$/.test(decoded) &&
    !/\s/.test(decoded) &&
    /[A-Za-z0-9]/.test(decoded)
  )
}

function hexDecode(hex) {
  const h = String(hex).replace(/[^0-9a-fA-F]/g, '')
  if (h.length % 2 !== 0) throw new Error('bad hex')
  if (typeof Buffer !== 'undefined') return Buffer.from(h, 'hex').toString('utf8')
  const bytes = new Uint8Array(h.length / 2)
  for (let i = 0; i < bytes.length; i++) bytes[i] = parseInt(h.substr(i * 2, 2), 16)
  if (typeof TextDecoder !== 'undefined') return new TextDecoder('utf-8').decode(bytes)
  let s = ''
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i])
  return s
}

/**
 * Strip non-ASCII watermarks (e.g. CJK anti-scrape) from API keys.
 * @param {string} key
 * @returns {string}
 */
function sanitizeApiKey(key) {
  if (!key) return key
  let k = String(key)
    .replace(/[\u200B-\u200D\uFEFF\u00AD\u2060]/g, '')
    .trim()
  if (/^[\x20-\x7E]+$/.test(k) && !/\s/.test(k)) {
    return k.replace(/\s+/g, '')
  }
  const stripped = k.replace(/[^\x20-\x7E]/g, '').replace(/\s+/g, '')
  if (stripped.length >= 8 && stripped.length <= 512 && KEY_PREFIX_RE.test(stripped)) {
    return stripped
  }
  return k
}

/** Non-sk tokens after key labels, or base64 after "base64：" / "俩次base64" style notes. */
function extractLooseKeys(text) {
  const out = []
  const vendor = text.match(VENDOR_KEY_RE)
  if (vendor) out.push(...vendor)

  // key：… / 密钥：… / base64：… / 两次base64：…
  const afterLabel = text.match(
    /(?:key|api[_-]?key|api\s*key|token|密钥|(?:俩|两|二)?次?\s*base\s*64|base\s*64)\s*[:：]\s*([A-Za-z0-9+/_-]{20,}={0,2})/gi,
  )
  if (afterLabel) {
    for (const chunk of afterLabel) {
      const m = chunk.match(/[:：]\s*([A-Za-z0-9+/_-]{20,}={0,2})/)
      if (m) {
        const decoded = decodeKeyBody(m[1])
        if (decoded) out.push(decoded)
      }
    }
  }
  return out
}

/**
 * Standalone base64 tokens that peel to sk- / g2a_ / tp- keys (incl. double base64).
 */
function extractBase64DecodedKeys(text) {
  const out = []
  const consider = (token) => {
    if (!token || token.startsWith('sk-') || token.startsWith('http')) return
    const decoded = decodeKeyBody(token)
    if (decoded && decoded !== token && hasKeyPrefix(decoded)) out.push(decoded)
  }

  for (const line of text.split(/\r?\n/)) {
    const t = line.trim()
    // whole line, or "label：TOKEN" on one line
    if (/^[A-Za-z0-9+/_-]{24,}={0,2}$/.test(t)) {
      consider(t)
      continue
    }
    // CJK-glued: …佬友们用dHAt… (no whitespace before base64)
    const cjkGlued = t.match(
      /(?:[一-鿿]|[\s"'`：:，。；、！？])([A-Za-z0-9+/]{32,}={0,2})\s*$/,
    )
    if (cjkGlued) consider(cjkGlued[1])
    const labeled = t.match(
      /(?:key|api[_-]?key|token|密钥|base\s*64|(?:俩|两|二)?次?\s*base\s*64)\s*[:：]\s*([A-Za-z0-9+/_-]{24,}={0,2})\s*$/i,
    )
    if (labeled) consider(labeled[1])
  }

  const re = new RegExp(`${B64_BOUNDARY_L}([A-Za-z0-9+/]{32,}={0,2})${B64_BOUNDARY_R}`, 'gm')
  let m
  while ((m = re.exec(text)) !== null) consider(m[1])
  return unique(out)
}

function pickBestUrl(urls, text) {
  if (urls.length === 0) return null
  const scored = urls.map((u) => {
    let s = 0
    const lower = u.toLowerCase()
    if (/anthropic|claude/.test(lower)) s += 3
    if (/openai|codex/.test(lower)) s += 2
    if (/api\./.test(lower)) s += 1
    if (/127\.0\.0\.1|localhost/.test(lower)) s += 1 // local proxy common
    // proximity to key words in original text
    if (new RegExp(`(?:BASE_URL|endpoint|baseUrl)[^\\n]{0,40}${escapeRegExp(u.slice(0, 30))}`, 'i').test(text)) {
      s += 2
    }
    return { u, s }
  })
  scored.sort((a, b) => b.s - a.s)
  return scored[0].u
}

function pickBestKey(keys) {
  if (keys.length === 0) return null
  const scored = keys.map((k) => {
    let s = k.length / 100
    if (k.startsWith('sk-ant-')) s += 3
    else if (k.startsWith('sk-')) s += 2
    else if (/^(?:g2a_|tp-)/i.test(k)) s += 2
    else if (/^[A-Za-z0-9+/]+={1,2}$/.test(k) && k.length >= 24) s += 0.5 // raw b64
    return { k, s }
  })
  scored.sort((a, b) => b.s - a.s)
  return maybeDecodeKey(scored[0].k)
}

function cleanUrl(u) {
  return String(u || '')
    .trim()
    // trailing JSON / prose punctuation (Discourse selection often keeps the closing quote)
    .replace(/[.,;:!?）)」』】"'`]+$/g, '')
    .replace(/^["'`]+/, '')
}

function scoreFields(fields, app) {
  let s = 0.3
  if (fields.endpoint) s += 0.35
  if (fields.apiKey) s += 0.35
  if (app) s += 0.1
  return Math.min(1, s)
}

function buildWarnings(fields) {
  const w = []
  if (fields.endpoint && !fields.apiKey) w.push('未识别到 API Key，仍可尝试导入')
  if (!fields.endpoint && fields.apiKey) w.push('未识别到 endpoint/base URL，仍可尝试导入')
  if (fields.endpoint && !/^https?:\/\//i.test(fields.endpoint)) {
    w.push('endpoint 不是 http(s) URL')
  }
  return w
}

function matchAll(text, re) {
  const out = []
  const r = new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g')
  let m
  while ((m = r.exec(text)) !== null) out.push(m[0])
  return out
}

function matchAllGroups(text, re, group) {
  const out = []
  const r = new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g')
  let m
  while ((m = r.exec(text)) !== null) out.push(m[group])
  return out
}

function unique(arr) {
  return [...new Set(arr.filter(Boolean))]
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function base64Encode(str) {
  if (typeof Buffer !== 'undefined') {
    return Buffer.from(str, 'utf8').toString('base64')
  }
  // browser
  return btoa(unescape(encodeURIComponent(str)))
}

function base64Decode(b64) {
  // normalize url-safe
  let s = String(b64 || '').replace(/-/g, '+').replace(/_/g, '/')
  // Reject oversized tokens before allocating decoded buffers
  if (s.length * 0.75 > MAX_DECODED_LEN) {
    throw new Error('base64 payload too large')
  }
  const pad = s.length % 4
  if (pad) s += '='.repeat(4 - pad)
  let out
  if (typeof Buffer !== 'undefined') {
    out = Buffer.from(s, 'base64').toString('utf8')
  } else {
    out = decodeURIComponent(escape(atob(s)))
  }
  if (out.length > MAX_DECODED_LEN) throw new Error('decoded payload too large')
  return out
}



  // ─── model extractor ───
/**
 * Extract model names from share text for CC Switch deep link.
 * Used by Node tests and inlined into the Tampermonkey userscript.
 */

/**
 * @typedef {{
 *   model: string|null,
 *   haikuModel: string|null,
 *   sonnetModel: string|null,
 *   opusModel: string|null,
 *   models: string[]
 * }} ModelResult
 */

/**
 * Ordered specific → general. Overlaps are resolved by keeping the longest
 * match at each span (e.g. claude-sonnet-4.5 wins over claude-sonnet-4).
 * @type {RegExp[]}
 */
const MODEL_RES = [
  // Claude (longer / more specific first)
  /claude-3\.5-sonnet(?:-\d{8})?/gi,
  /claude-3-sonnet(?:-\d{8})?/gi,
  /claude-3\.5-haiku(?:-\d{8})?/gi,
  /claude-3-haiku(?:-\d{8})?/gi,
  /claude-3-opus(?:-\d{8})?/gi,
  /claude-sonnet-4\.5/gi,
  /claude-opus-4\.8/gi,
  /claude-sonnet-4(?!\.\d)/gi,
  /claude-opus-4(?!\.\d)/gi,
  /\bclaude-sonnet\b/gi,
  /\bclaude-haiku\b/gi,
  /\bclaude-opus\b/gi,
  // OpenAI
  /gpt-5\.?6-sol/gi,
  /gpt-5\.?5/gi,
  /gpt-4\.?5[a-z-]*(?:turbo|preview)?/gi,
  /gpt-4o(?:-mini|-preview)?/gi,
  /gpt-4-turbo(?:-preview)?/gi,
  /gpt-4-vision(?:-preview)?/gi,
  /gpt-4(?:-\d{4})?(?![a-z0-9.])/gi,
  /gpt-3\.5-turbo(?:-\d{4})?/gi,
  /\bo3(?:-mini)?\b/gi,
  /\bo1(?:-mini|-preview)?\b/gi,
  // Grok — accept "Grok4.5" / "grok4.5" (no hyphen)
  /(?<![a-z0-9])grok[-_]?4\.5(?![0-9])/gi,
  /(?<![a-z0-9])grok[-_]?3\.5(?![0-9])/gi,
  /(?<![a-z0-9])grok[-_]?4(?![0-9.])/gi,
  /(?<![a-z0-9])grok[-_]?3(?![0-9.])/gi,
  /(?<![a-z0-9])grok-beta\b/gi,
  /(?<![a-z0-9])grok-2\b/gi,
  // Gemini
  /gemini-2\.5-(?:pro|flash)/gi,
  /gemini-2\.0-(?:flash|pro)/gi,
  /gemini-1\.5-(?:pro|flash)/gi,
  /gemini-pro/gi,
  /gemini-flash/gi,
  // DeepSeek — require full minor when present so deepseek-v3.2 is not truncated
  /deepseek-v3(?:\.\d+)?/gi,
  /deepseek-coder(?:-v2)?/gi,
  /deepseek-chat/gi,
]

/**
 * @param {string} text
 * @returns {ModelResult}
 */
function extractModels(text) {
  if (!text) {
    return { model: null, haikuModel: null, sonnetModel: null, opusModel: null, models: [] }
  }

  // Mask secrets / long base64 so tokens like "...o3..." inside keys never become models
  const scanText = String(text)
    .replace(/[A-Za-z0-9+/_-]{24,}={0,2}/g, ' ')
    .replace(/\bsk-(?:ant-)?[A-Za-z0-9_-]{8,}\b/gi, ' ')
    .replace(/\b(?:g2a_|tp-|nk-|pk-|rk-)[A-Za-z0-9_-]{8,}\b/gi, ' ')

  /** @type {Array<{start: number, end: number, value: string}>} */
  const spans = []
  for (const re of MODEL_RES) {
    const r = new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g')
    let m
    while ((m = r.exec(scanText)) !== null) {
      const value = normalizeModelId(m[0])
      if (!value) continue
      spans.push({ start: m.index, end: m.index + m[0].length, value })
    }
  }

  // Prefer longer matches; drop spans fully contained in a longer one
  spans.sort((a, b) => b.end - b.start - (a.end - a.start) || a.start - b.start)
  /** @type {Array<{start: number, end: number, value: string}>} */
  const kept = []
  for (const s of spans) {
    const contained = kept.some((k) => s.start >= k.start && s.end <= k.end)
    if (!contained) kept.push(s)
  }

  // Stable unique list in document order
  kept.sort((a, b) => a.start - b.start)
  const models = []
  const seen = new Set()
  for (const s of kept) {
    if (seen.has(s.value)) continue
    seen.add(s.value)
    models.push(s.value)
  }

  // Claude-specific: map to tier fields (prefer longer / more specific ids)
  let haikuModel = null
  let sonnetModel = null
  let opusModel = null
  for (const m of models) {
    if (/haiku/i.test(m)) {
      if (!haikuModel || m.length > haikuModel.length) haikuModel = m
    } else if (/sonnet/i.test(m)) {
      if (!sonnetModel || m.length > sonnetModel.length) sonnetModel = m
    } else if (/opus/i.test(m)) {
      if (!opusModel || m.length > opusModel.length) opusModel = m
    }
  }

  // Primary model: prefer sonnet > opus > haiku > first found
  const model = sonnetModel || opusModel || haikuModel || models[0] || null

  return { model, haikuModel, sonnetModel, opusModel, models }
}

/**
 * Normalize informal spellings to stable model ids.
 * e.g. Grok4.5 / grok4.5 → grok-4.5; gpt5.5 → gpt-5.5 (when matched that way)
 * @param {string} raw
 * @returns {string}
 */
function normalizeModelId(raw) {
  let m = String(raw || '').toLowerCase().trim()
  // Grok: "Grok4.5" / "grok4.5" / "grok_4.5" → "grok-4.5"
  m = m.replace(/^grok[_-]?(\d)/, 'grok-$1')
  // gpt5.5 → gpt-5.5 when hyphen missing
  m = m.replace(/^gpt(\d)/, 'gpt-$1')
  return m
}

/**
 * Soft preference sort for UI dropdowns. Relay shares mix vendors freely, so we
 * never drop models by app — only put preferred families first.
 * @param {string[]} models
 * @param {'claude'|'codex'|null} app
 * @returns {string[]}
 */
function filterModelsForApp(models, app) {
  if (!app || !models.length) return models.slice()

  const prefer =
    app === 'claude'
      ? (m) => /claude/i.test(m)
      : app === 'codex'
        ? (m) => /gpt|o1|o3|codex/i.test(m)
        : () => false

  return models.slice().sort((a, b) => Number(prefer(b)) - Number(prefer(a)))
}


  global.__CCS_CORE_READY__ = true;

  // ─── ui ───
/* UI + integration (concatenated after core by scripts/build.mjs) */
;(function () {
  'use strict'

  const ROOT_ID = 'ccs-ld-root'
  const Z = 2147483000

  let lastSelectionText = ''
  let hideTimer = null
  let selectedApp = null
  let currentResult = null
  let currentModelInfo = null
  let currentDeeplink = null
  /** @type {string|null} */
  let selectedModel = null

  function ensureRoot() {
    let host = document.getElementById(ROOT_ID)
    if (host) return host.shadowRoot
    host = document.createElement('div')
    host.id = ROOT_ID
    host.style.all = 'initial'
    host.style.position = 'fixed'
    host.style.zIndex = String(Z)
    host.style.top = '0'
    host.style.left = '0'
    host.style.width = '0'
    host.style.height = '0'
    document.documentElement.appendChild(host)
    const shadow = host.attachShadow({ mode: 'open' })
    const style = document.createElement('style')
    style.textContent = CSS_TEXT
    shadow.appendChild(style)
    return shadow
  }

  const CSS_TEXT = `
    :host { all: initial; }
    * { box-sizing: border-box; font-family: system-ui, -apple-system, "Segoe UI", Roboto, "PingFang SC", "Microsoft YaHei", sans-serif; }
    .ccs-btn {
      position: fixed;
      z-index: ${Z};
      padding: 8px 14px;
      border: none;
      border-radius: 999px;
      background: #228be6;
      color: #fff;
      font-size: 12px;
      font-weight: 600;
      cursor: pointer;
      box-shadow: 0 4px 16px rgba(0,0,0,.28);
      display: none;
      white-space: nowrap;
    }
    .ccs-btn:hover { background: #1c7ed6; }
    .ccs-btn.show { display: inline-flex; align-items: center; gap: 6px; }
    .ccs-overlay {
      position: fixed; inset: 0; background: rgba(0,0,0,.45);
      z-index: ${Z + 1}; display: none; align-items: center; justify-content: center;
      padding: 16px;
    }
    .ccs-overlay.show { display: flex; }
    .ccs-card {
      width: min(380px, 100%);
      background: #2c2e33;
      color: #e9ecef;
      border-radius: 12px;
      border: 1px solid #373a40;
      box-shadow: 0 12px 40px rgba(0,0,0,.45);
      padding: 16px;
    }
    .ccs-card h2 { margin: 0 0 6px; font-size: 15px; font-weight: 650; color: #fff; }
    .ccs-meta { font-size: 12px; color: #adb5bd; margin-bottom: 12px; line-height: 1.5; }
    .ccs-fields {
      background: #1a1b1e; border-radius: 8px; padding: 10px 12px;
      font-size: 12px; line-height: 1.65; margin-bottom: 12px;
      word-break: break-all;
    }
    .ccs-fields .k { color: #868e96; margin-right: 6px; }
    .ccs-warn {
      font-size: 11px; color: #fcc419; margin: -4px 0 12px; line-height: 1.45;
    }
    .ccs-row {
      display: flex; align-items: center; gap: 8px; margin-bottom: 10px;
      font-size: 12px;
    }
    .ccs-row label { color: #adb5bd; white-space: nowrap; }
    .ccs-row select {
      flex: 1; min-width: 0;
      background: #1a1b1e; color: #e9ecef; border: 1px solid #495057;
      border-radius: 6px; padding: 6px 8px; font-size: 12px;
    }
    .ccs-cand {
      display: none; align-items: center; gap: 8px; margin-bottom: 10px;
      font-size: 12px; color: #ced4da;
    }
    .ccs-cand.show { display: flex; }
    .ccs-cand button {
      border: 1px solid #495057; background: #373a40; color: #fff;
      border-radius: 6px; padding: 4px 10px; font-size: 12px; cursor: pointer;
    }
    .ccs-cand button:disabled { opacity: .4; cursor: not-allowed; }
    .ccs-cand .ccs-cand-label { flex: 1; text-align: center; color: #adb5bd; }
    .ccs-apps { display: flex; gap: 8px; margin-bottom: 12px; }
    .ccs-apps button {
      flex: 1; border: 1px solid #495057; background: #373a40; color: #ced4da;
      border-radius: 8px; padding: 8px; font-size: 12px; cursor: pointer;
    }
    .ccs-apps button.active {
      background: #228be6; border-color: #228be6; color: #fff; font-weight: 600;
    }
    .ccs-apps button:disabled { opacity: .5; cursor: not-allowed; }
    .ccs-actions { display: flex; gap: 8px; flex-wrap: wrap; }
    .ccs-actions button {
      flex: 1; min-width: 90px; border-radius: 8px; padding: 9px 10px;
      font-size: 12px; cursor: pointer; border: 1px solid transparent;
    }
    .ccs-btn-cancel { background: transparent; border-color: #495057 !important; color: #adb5bd; }
    .ccs-btn-copy { background: #495057; color: #fff; }
    .ccs-btn-open { background: #40c057; color: #fff; font-weight: 600; }
    .ccs-btn-open:disabled { opacity: .45; cursor: not-allowed; }
    .ccs-toast {
      position: fixed; left: 50%; bottom: 28px; transform: translateX(-50%);
      background: #212529; color: #fff; padding: 10px 16px; border-radius: 8px;
      font-size: 12px; z-index: ${Z + 2}; opacity: 0; pointer-events: none;
      transition: opacity .2s ease; max-width: min(420px, 92vw); text-align: center;
      box-shadow: 0 6px 20px rgba(0,0,0,.35);
    }
    .ccs-toast.show { opacity: 1; }
    .ccs-err {
      color: #ff6b6b; font-size: 13px; padding: 8px 0 12px; line-height: 1.5;
    }
  `

  function getUi() {
    const shadow = ensureRoot()
    let btn = shadow.getElementById('btn')
    let overlay = shadow.getElementById('overlay')
    let toast = shadow.getElementById('toast')
    if (!btn) {
      btn = document.createElement('button')
      btn.id = 'btn'
      btn.className = 'ccs-btn'
      btn.type = 'button'
      btn.textContent = '导入 ccSwitch'
      btn.addEventListener('mousedown', (e) => e.preventDefault())
      btn.addEventListener('click', onImportClick)
      shadow.appendChild(btn)

      overlay = document.createElement('div')
      overlay.id = 'overlay'
      overlay.className = 'ccs-overlay'
      overlay.innerHTML = `
        <div class="ccs-card" role="dialog" aria-modal="true">
          <h2>导入到 CC Switch</h2>
          <div class="ccs-meta" id="meta"></div>
          <div class="ccs-err" id="err" style="display:none"></div>
          <div class="ccs-fields" id="fields"></div>
          <div class="ccs-cand" id="cand">
            <button type="button" id="cand-prev" aria-label="上一组候选">‹</button>
            <span class="ccs-cand-label" id="cand-label">候选 1/1</span>
            <button type="button" id="cand-next" aria-label="下一组候选">›</button>
          </div>
          <div class="ccs-row" id="model-row" style="display:none">
            <label for="model-select">model</label>
            <select id="model-select"></select>
          </div>
          <div class="ccs-warn" id="warn"></div>
          <div class="ccs-apps">
            <button type="button" data-app="claude" id="app-claude">Claude Code</button>
            <button type="button" data-app="codex" id="app-codex">Codex</button>
          </div>
          <div class="ccs-actions">
            <button type="button" class="ccs-btn-cancel" id="cancel">取消</button>
            <button type="button" class="ccs-btn-copy" id="copy">复制深链</button>
            <button type="button" class="ccs-btn-open" id="open">打开导入</button>
          </div>
        </div>
      `
      overlay.addEventListener('click', (e) => {
        if (e.target === overlay) closeCard()
      })
      shadow.appendChild(overlay)

      toast = document.createElement('div')
      toast.id = 'toast'
      toast.className = 'ccs-toast'
      shadow.appendChild(toast)

      shadow.getElementById('cancel').addEventListener('click', closeCard)
      shadow.getElementById('copy').addEventListener('click', () => copyDeeplink(true))
      shadow.getElementById('open').addEventListener('click', openImport)
      shadow.getElementById('app-claude').addEventListener('click', () => setApp('claude'))
      shadow.getElementById('app-codex').addEventListener('click', () => setApp('codex'))
      shadow.getElementById('cand-prev').addEventListener('click', () => shiftCandidate(-1))
      shadow.getElementById('cand-next').addEventListener('click', () => shiftCandidate(1))
      shadow.getElementById('model-select').addEventListener('change', onModelSelect)
    }
    return { shadow, btn, overlay, toast }
  }

  function showToast(msg, ms = 2800) {
    const { toast } = getUi()
    toast.textContent = msg
    toast.classList.add('show')
    clearTimeout(showToast._t)
    showToast._t = setTimeout(() => toast.classList.remove('show'), ms)
  }

  function getSelectionText() {
    const sel = window.getSelection()
    if (!sel || sel.isCollapsed) return ''
    const plain = String(sel.toString() || '').trim()
    if (!plain) return ''
    const anchors = collectAnchorsInSelection(sel)
    if (typeof enrichTextWithAnchorHrefs === 'function') {
      return String(enrichTextWithAnchorHrefs(plain, anchors) || plain).trim()
    }
    return plain
  }

  /**
   * @param {Selection} sel
   * @returns {Array<{text: string, href: string}>}
   */
  function collectAnchorsInSelection(sel) {
    const out = []
    if (!sel || sel.rangeCount === 0) return out
    const seen = new Set()
    for (let i = 0; i < sel.rangeCount; i++) {
      const range = sel.getRangeAt(i)
      const root = range.commonAncestorContainer
      const rootEl =
        root.nodeType === 1 /* ELEMENT_NODE */ ? root : root.parentElement
      if (!rootEl) continue

      let nearest = rootEl.closest ? rootEl.closest('a[href]') : null
      if (!nearest && rootEl.tagName === 'A' && rootEl.getAttribute('href')) {
        nearest = rootEl
      }
      if (nearest) pushAnchor(nearest, out, seen)

      const candidates = rootEl.querySelectorAll
        ? rootEl.querySelectorAll('a[href]')
        : []
      for (const a of candidates) {
        if (!rangeIntersectsNode(range, a)) continue
        pushAnchor(a, out, seen)
      }

      for (const boundary of [range.startContainer, range.endContainer]) {
        const el =
          boundary.nodeType === 1 ? boundary : boundary.parentElement
        if (!el) continue
        const a = el.closest ? el.closest('a[href]') : null
        if (a) pushAnchor(a, out, seen)
      }
    }
    return out
  }

  function pushAnchor(a, out, seen) {
    if (!a || !a.getAttribute) return
    const href = a.href || a.getAttribute('href') || ''
    if (!href) return
    const key = href + '|' + (a.textContent || '').trim()
    if (seen.has(key)) return
    seen.add(key)
    out.push({
      text: String(a.textContent || '').replace(/\s+/g, ' ').trim(),
      href: String(href),
    })
  }

  function rangeIntersectsNode(range, node) {
    if (!range || !node) return false
    try {
      if (typeof range.intersectsNode === 'function') {
        return range.intersectsNode(node)
      }
    } catch {
      /* fall through */
    }
    try {
      const nodeRange = document.createRange()
      nodeRange.selectNode(node)
      return (
        range.compareBoundaryPoints(Range.END_TO_START, nodeRange) < 0 &&
        range.compareBoundaryPoints(Range.START_TO_END, nodeRange) > 0
      )
    } catch {
      return false
    }
  }

  function getSelectionRect() {
    const sel = window.getSelection()
    if (!sel || sel.rangeCount === 0) return null
    const range = sel.getRangeAt(0)
    const rect = range.getBoundingClientRect()
    if (!rect || (rect.width === 0 && rect.height === 0)) return null
    return rect
  }

  function positionButton(rect) {
    const { btn } = getUi()
    const top = Math.min(window.innerHeight - 48, Math.max(8, rect.bottom + 8))
    const left = Math.min(window.innerWidth - 140, Math.max(8, rect.left + rect.width / 2 - 60))
    btn.style.top = `${top}px`
    btn.style.left = `${left}px`
  }

  function updateSelectionUi() {
    const text = getSelectionText()
    lastSelectionText = text
    const { btn } = getUi()
    if (!text || !looksLikeConfig(text)) {
      btn.classList.remove('show')
      return
    }
    const rect = getSelectionRect()
    if (!rect) {
      btn.classList.remove('show')
      return
    }
    positionButton(rect)
    btn.classList.add('show')
  }

  function scheduleUpdate() {
    clearTimeout(hideTimer)
    hideTimer = setTimeout(updateSelectionUi, 120)
  }

  function onImportClick(e) {
    e.preventDefault()
    e.stopPropagation()
    const text = lastSelectionText || getSelectionText()
    const { btn } = getUi()
    btn.classList.remove('show')

    const result = parseShareText(text)
    if (!result) {
      openErrorCard('未识别到 API 配置。请选中包含 base URL / API Key / ccswitch 深链 / Base64 配置 的文本。')
      return
    }
    currentResult = result
    selectedApp = result.app
    selectedModel = null
    refreshModelInfo(text)
    rebuildDeeplink()
    renderCard(result)
  }

  /**
   * Recompute models for current app (filters by app when possible).
   * @param {string} [sourceText]
   */
  function refreshModelInfo(sourceText) {
    const text = sourceText || lastSelectionText || ''
    let info =
      typeof extractModels === 'function'
        ? extractModels(text)
        : { model: null, haikuModel: null, sonnetModel: null, opusModel: null, models: [] }

    let models = info.models || []
    if (typeof filterModelsForApp === 'function' && selectedApp) {
      models = filterModelsForApp(models, selectedApp)
    }

    if (selectedModel && models.includes(selectedModel)) {
      info = { ...info, models, model: selectedModel }
    } else if (models.length === 1) {
      selectedModel = models[0]
      info = { ...info, models, model: models[0] }
    } else if (models.length > 1) {
      const preferred =
        (info.model && models.includes(info.model) && info.model) ||
        models.find((m) => /sonnet/i.test(m)) ||
        models[0]
      selectedModel = preferred
      info = { ...info, models, model: preferred }
    } else {
      selectedModel = null
      info = {
        model: null,
        haikuModel: null,
        sonnetModel: null,
        opusModel: null,
        models: [],
      }
    }

    if (selectedApp === 'claude') {
      info.haikuModel = models.find((m) => /haiku/i.test(m)) || null
      info.sonnetModel = models.find((m) => /sonnet/i.test(m)) || null
      info.opusModel = models.find((m) => /opus/i.test(m)) || null
    } else {
      info.haikuModel = null
      info.sonnetModel = null
      info.opusModel = null
    }

    currentModelInfo = info
  }

  function openErrorCard(msg) {
    const { overlay, shadow } = getUi()
    shadow.getElementById('meta').textContent = ''
    shadow.getElementById('fields').style.display = 'none'
    shadow.getElementById('warn').textContent = ''
    shadow.getElementById('cand').classList.remove('show')
    shadow.getElementById('model-row').style.display = 'none'
    const err = shadow.getElementById('err')
    err.style.display = 'block'
    err.textContent = msg
    shadow.getElementById('app-claude').disabled = true
    shadow.getElementById('app-codex').disabled = true
    shadow.getElementById('open').disabled = true
    shadow.getElementById('copy').disabled = true
    overlay.classList.add('show')
  }

  function renderCard(result) {
    const { overlay, shadow } = getUi()
    const err = shadow.getElementById('err')
    err.style.display = 'none'
    err.textContent = ''
    shadow.getElementById('fields').style.display = 'block'
    shadow.getElementById('app-claude').disabled = false
    shadow.getElementById('app-codex').disabled = false
    shadow.getElementById('copy').disabled = false

    const conf = Math.round((result.confidence || 0) * 100)
    const modelCount = currentModelInfo?.models?.length || 0
    const candCount = result.candidates?.length || result.candidateCount || 1
    const candIdx = (result.candidateIndex || 0) + 1
    const ver =
      typeof SCRIPT_VERSION !== 'undefined' && SCRIPT_VERSION ? String(SCRIPT_VERSION) : 'dev'
    shadow.getElementById('meta').textContent =
      `识别：${result.source} · 置信度 ${conf}%` +
      (candCount > 1 ? ` · 候选 ${candIdx}/${candCount}` : '') +
      (modelCount ? ` · 模型×${modelCount}` : '') +
      ` · v${ver}`

    const modelLine = currentModelInfo?.model
      ? escapeHtml(currentModelInfo.model) +
        (modelCount > 1
          ? ` <span style="opacity:.65">(+${modelCount - 1})</span>`
          : '')
      : modelCount
        ? escapeHtml(currentModelInfo.models.slice(0, 3).join(', ')) +
          (modelCount > 3 ? '…' : '')
        : '—'

    const fields = shadow.getElementById('fields')
    fields.innerHTML = `
      <div><span class="k">name</span>${escapeHtml(result.name || '')}</div>
      <div><span class="k">endpoint</span>${escapeHtml(result.endpoint || '—')}</div>
      <div><span class="k">apiKey</span>${escapeHtml(maskKey(result.apiKey || '') || '—')}</div>
      <div><span class="k">model</span>${modelLine}</div>
      <div><span class="k">app</span>${escapeHtml(selectedApp || '未选择')}</div>
    `

    const candEl = shadow.getElementById('cand')
    if (candCount > 1 && result.candidates && result.candidates.length > 1) {
      candEl.classList.add('show')
      shadow.getElementById('cand-label').textContent = `候选 ${candIdx}/${candCount}`
      shadow.getElementById('cand-prev').disabled = (result.candidateIndex || 0) <= 0
      shadow.getElementById('cand-next').disabled =
        (result.candidateIndex || 0) >= result.candidates.length - 1
    } else {
      candEl.classList.remove('show')
    }

    const modelRow = shadow.getElementById('model-row')
    const modelSelect = shadow.getElementById('model-select')
    if (modelCount > 1) {
      modelRow.style.display = 'flex'
      modelSelect.innerHTML = currentModelInfo.models
        .map(
          (m) =>
            `<option value="${escapeHtml(m)}"${m === currentModelInfo.model ? ' selected' : ''}>${escapeHtml(m)}</option>`,
        )
        .join('')
    } else {
      modelRow.style.display = 'none'
      modelSelect.innerHTML = ''
    }

    const warn = shadow.getElementById('warn')
    const warnings = [...(result.warnings || [])]
    if (!selectedApp) warnings.push('请选择导入到 Claude Code 或 Codex')
    if (modelCount === 1) warnings.push('已自动填入检测到的唯一模型')
    else if (modelCount > 1) warnings.push(`检测到 ${modelCount} 个模型，可在下方切换`)
    warn.textContent = warnings.join('；')

    syncAppButtons()
    shadow.getElementById('open').disabled = !selectedApp
    overlay.classList.add('show')
  }

  function shiftCandidate(delta) {
    if (!currentResult || typeof selectCandidate !== 'function') return
    const list = currentResult.candidates
    if (!list || list.length < 2) return
    const next = selectCandidate(currentResult, (currentResult.candidateIndex || 0) + delta)
    currentResult = next
    rebuildDeeplink()
    renderCard(next)
  }

  function onModelSelect(e) {
    const v = e.target && e.target.value
    selectedModel = v || null
    if (currentModelInfo) {
      currentModelInfo = { ...currentModelInfo, model: selectedModel }
    }
    rebuildDeeplink()
    if (currentResult) renderCard(currentResult)
  }

  function setApp(app) {
    selectedApp = app
    refreshModelInfo()
    rebuildDeeplink()
    if (currentResult) renderCard(currentResult)
  }

  function syncAppButtons() {
    const { shadow } = getUi()
    shadow.getElementById('app-claude').classList.toggle('active', selectedApp === 'claude')
    shadow.getElementById('app-codex').classList.toggle('active', selectedApp === 'codex')
  }

  function rebuildDeeplink() {
    currentDeeplink = null
    if (!currentResult || !selectedApp) return
    try {
      const modelInfo = currentModelInfo
        ? { ...currentModelInfo, model: selectedModel || currentModelInfo.model }
        : null
      currentDeeplink = buildDeeplink(currentResult, selectedApp, modelInfo)
    } catch (e) {
      currentDeeplink = null
    }
  }

  function closeCard() {
    const { overlay } = getUi()
    overlay.classList.remove('show')
  }

  function copyText(text) {
    if (typeof GM_setClipboard === 'function') {
      GM_setClipboard(text, 'text')
      return Promise.resolve(true)
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text).then(() => true).catch(() => false)
    }
    try {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.left = '-9999px'
      document.body.appendChild(ta)
      ta.select()
      const ok = document.execCommand('copy')
      document.body.removeChild(ta)
      return Promise.resolve(ok)
    } catch {
      return Promise.resolve(false)
    }
  }

  function copyDeeplink(fromBtn) {
    if (!currentDeeplink) {
      showToast('请先选择 Claude Code 或 Codex')
      return
    }
    copyText(currentDeeplink).then((ok) => {
      showToast(ok ? '深链已复制到剪贴板' : '复制失败，请手动复制')
      if (fromBtn && typeof GM_notification === 'function') {
        try {
          GM_notification({ title: 'CC Switch Importer', text: '深链已复制', timeout: 2000 })
        } catch (_) {}
      }
    })
  }

  function openImport() {
    if (!selectedApp) {
      showToast('请选择 Claude Code 或 Codex')
      return
    }
    rebuildDeeplink()
    if (!currentDeeplink) {
      showToast('无法生成深链')
      return
    }

    const link = currentDeeplink
    const a = document.createElement('a')
    a.href = link
    a.style.display = 'none'
    document.body.appendChild(a)
    try {
      a.click()
    } catch (_) {
      try {
        window.location.href = link
      } catch (_) {}
    }
    setTimeout(() => a.remove(), 0)

    // Do NOT auto-copy the deeplink (contains apiKey). Use「复制深链」if protocol fails.
    showToast('已尝试打开 CC Switch。若无反应，请点「复制深链」并确认已安装 CC Switch', 4200)
  }

  function escapeHtml(s) {
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
  }

  function onKeydown(e) {
    if (e.key === 'Escape') closeCard()
  }

  function init() {
    document.addEventListener('selectionchange', scheduleUpdate)
    document.addEventListener('mouseup', scheduleUpdate)
    document.addEventListener('keyup', scheduleUpdate)
    document.addEventListener('keydown', onKeydown)
    window.addEventListener('scroll', () => {
      const { btn } = getUi()
      if (btn.classList.contains('show')) updateSelectionUi()
    }, true)
    getUi()
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init)
  } else {
    init()
  }
})()


})(typeof unsafeWindow !== 'undefined' ? unsafeWindow : window);
