/**
 * Bundle core + model-extractor + ui-main into a single Tampermonkey userscript.
 * Version is read from package.json so header / UI stay in sync.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const corePath = path.join(root, 'userscript/lib/core.mjs')
const modelPath = path.join(root, 'userscript/lib/model-extractor.mjs')
const uiPath = path.join(root, 'userscript/ui-main.js')
const outPath = path.join(root, 'userscript/ccswitch-linuxdo-importer.user.js')
const pkgPath = path.join(root, 'package.json')

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
const version = String(pkg.version || '0.0.0')
const rawBase =
  'https://raw.githubusercontent.com/Super-YYQ/ccswitch-linuxdo-importer/main/userscript/ccswitch-linuxdo-importer.user.js'

function stripExports(src) {
  return src
    .replace(/^export function /gm, 'function ')
    .replace(/^export \{[^}]+\}\s*$/gm, '')
    .replace(/^export const /gm, 'const ')
}

const core = stripExports(fs.readFileSync(corePath, 'utf8'))
const model = stripExports(fs.readFileSync(modelPath, 'utf8'))
const ui = fs.readFileSync(uiPath, 'utf8')

const header = `// ==UserScript==
// @name         CC Switch Importer for linux.do
// @namespace    https://github.com/Super-YYQ/ccswitch-linuxdo-importer
// @version      ${version}
// @description  选中 linux.do 分享文本，一键导入 CC Switch（Claude Code / Codex，自动识别模型）
// @author       CC Switch Importer Contributors
// @match        https://linux.do/*
// @match        https://www.linux.do/*
// @grant        GM_setClipboard
// @grant        GM_notification
// @run-at       document-idle
// @noframes
// @license      MIT
// @homepageURL  https://github.com/Super-YYQ/ccswitch-linuxdo-importer
// @supportURL   https://github.com/Super-YYQ/ccswitch-linuxdo-importer/issues
// @downloadURL  ${rawBase}
// @updateURL    ${rawBase}
// ==/UserScript==

/* eslint-disable */
/* generated by scripts/build.mjs — edit userscript/lib/* + ui-main.js then rebuild */
`

const body = `
;(function (global) {
  'use strict';

  const SCRIPT_VERSION = ${JSON.stringify(version)};

  // ─── core (parse / classify / deeplink) ───
${core}

  // ─── model extractor ───
${model}

  global.__CCS_CORE_READY__ = true;

  // ─── ui ───
${ui}

})(typeof unsafeWindow !== 'undefined' ? unsafeWindow : window);
`

fs.writeFileSync(outPath, header + body, 'utf8')
console.log('Wrote', outPath, `(v${version})`)
