/**
 * Bundle userscript/lib/core.mjs + userscript/ui-main.js
 * into a single Tampermonkey userscript.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const corePath = path.join(root, 'userscript/lib/core.mjs')
const uiPath = path.join(root, 'userscript/ui-main.js')
const outPath = path.join(root, 'userscript/ccswitch-linuxdo-importer.user.js')

let core = fs.readFileSync(corePath, 'utf8')

// Strip ES module exports for IIFE embedding
core = core
  .replace(/^export function /gm, 'function ')
  .replace(/^export \{[^}]+\}\s*$/gm, '')
  .replace(/^export const /gm, 'const ')

const ui = fs.readFileSync(uiPath, 'utf8')

const header = `// ==UserScript==
// @name         CC Switch Importer for linux.do
// @namespace    https://github.com/yanyaqi/ccswitch-linuxdo-importer
// @version      1.0.1
// @description  在 linux.do 选中 API 分享文本，解析后通过 ccswitch:// 导入 CC Switch（Claude Code / Codex）
// @author       yanyaqi
// @match        https://linux.do/*
// @match        https://www.linux.do/*
// @grant        GM_setClipboard
// @grant        GM_notification
// @run-at       document-idle
// @noframes
// ==/UserScript==

/* eslint-disable */
/* generated by scripts/build.mjs — edit userscript/lib/core.mjs + userscript/ui-main.js then rebuild */
`

const body = `
;(function (global) {
  'use strict';

  // ─── core (parse / classify / deeplink) ───
${core}

  // expose pure fns for ui-main (same scope)
  global.__CCS_CORE_READY__ = true;

  // ─── ui ───
${ui}

})(typeof unsafeWindow !== 'undefined' ? unsafeWindow : window);
`

// ui-main references parseShareText etc. in outer IIFE scope — good if we don't nest extra function for core.
// Actually ui is wrapped in its own IIFE and won't see core functions!
// Fix: don't wrap core separately; inject core into same scope as ui by NOT wrapping core in nested function.
// Restructure: single IIFE with core then ui without ui's outer wrapper dependency.

fs.writeFileSync(outPath, header + body, 'utf8')
console.log('Wrote', outPath)
